name: React Native Android CI/CD with Fastlane

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR creation to the main branch
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu to build Android APK

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Choose the appropriate Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Set up Android SDK
      - name: Set up Android SDK
        uses: reactivecircus/android-sdk-installer-action@v2
        with:
          api-level: 30  # Specify the API level you need

      
      # Step 6: Install Fastlane
      - name: Install Fastlane
        run: |
          gem install fastlane

      # Step 7: Run Fastlane to build the APK
      - name: Build release APK with Fastlane
        run: |
          cd android
          fastlane build_release  # Trigger the Fastlane lane to build APK
